# Workflow used to make a request to proxy.golang.org to refresh cache on https://pkg.go.dev/github.com/docker/buildx
# when a released of buildx is produced
name: godev

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      -
        name: Call pkg.go.dev
        run: |
          go get github.com/${GITHUB_REPOSITORY}@${GITHUB_REF#refs/tags/}
        env:
          GO111MODULE: on
          GOPROXY: https://proxy.golang.org
