name: validate

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'v[0-9]*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'v[0-9]*'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - lint
          - validate-vendor
          - validate-docs
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run
        run: |
          make ${{ matrix.target }}

  validate-docs-yaml:
    runs-on: ubuntu-latest
    needs:
      - validate
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run
        run: |
          make docs
        env:
          FORMATS: yaml
